export function init(container) {
  container.innerHTML = `
    <style>
      .wr-wrapper {
        display: flex; flex-direction: column; align-items: center;
        width: 100%; max-width: 500px; margin: 0 auto;
        font-family: 'Outfit', sans-serif;
        color: #fff; padding: 10px 10px 30px;
        min-height: calc(100vh - 100px);
      }
      .wr-header {
        display: flex; justify-content: space-between; width: 100%;
        margin-bottom: 20px; font-weight: 800; font-size: 1.1rem;
      }
      .wr-score-box { background: rgba(255,255,255,0.1); padding: 8px 16px; border-radius: 20px; }
      
      .wr-board {
        display: grid; grid-template-rows: repeat(6, 1fr); gap: 6px;
        margin-bottom: 30px; width: 100%; max-width: 320px;
      }
      .wr-row {
        display: grid; grid-template-columns: repeat(5, 1fr); gap: 6px;
      }
      .wr-tile {
        width: 100%; aspect-ratio: 1; border: 2px solid rgba(255,255,255,0.2);
        display: flex; align-items: center; justify-content: center;
        font-size: 2rem; font-weight: 900; text-transform: uppercase;
        border-radius: 8px; transition: transform 0.2s;
      }
      
      /* States */
      .wr-tile.filled { border-color: rgba(255,255,255,0.6); animation: wr-pop 0.1s; }
      .wr-tile.correct { background: #10B981; border-color: #10B981; color: white; }
      .wr-tile.present { background: #F59E0B; border-color: #F59E0B; color: white; }
      .wr-tile.absent { background: #374151; border-color: #374151; color: white; opacity: 0.8; }
      
      /* Keyboard */
      .wr-keyboard {
        display: flex; flex-direction: column; gap: 8px; width: 100%; max-width: 450px;
      }
      .wr-key-row {
        display: flex; justify-content: center; gap: 6px; width: 100%;
      }
      .wr-key {
        flex: 1; background: #4B5563; border: none; border-radius: 6px;
        color: #fff; font-size: 1.1rem; font-weight: 700; cursor: pointer;
        height: 55px; display: flex; align-items: center; justify-content: center;
        text-transform: uppercase; user-select: none; transition: background 0.2s;
      }
      .wr-key:active { transform: scale(0.95); }
      .wr-key.large { flex: 1.5; font-size: 0.9rem; }
      
      .wr-key.correct { background: #10B981; }
      .wr-key.present { background: #F59E0B; }
      .wr-key.absent { background: #374151; opacity: 0.5; }

      /* Overlays */
      .wr-overlay {
        position: fixed; inset: 0; background: rgba(10,10,20,0.95);
        display: none; flex-direction: column; align-items: center; justify-content: center;
        z-index: 100; padding: 20px; text-align: center;
      }
      .wr-title { font-size: 3rem; font-weight: 900; margin-bottom: 10px; }
      .wr-target { font-size: 2rem; font-weight: 900; color: #10B981; margin-bottom: 30px; letter-spacing: 5px;}
      .wr-btn {
        background: #38BDF8; color: #000; border: none; padding: 18px 40px;
        border-radius: 50px; font-size: 1.3rem; font-weight: 900; cursor: pointer;
        width: 100%; max-width: 300px; margin-bottom: 15px; box-shadow: 0 8px 25px rgba(56,189,248,0.4);
      }
      
      .wr-toast {
        position: fixed; top: 100px; left: 50%; transform: translateX(-50%);
        background: white; color: black; padding: 10px 20px; border-radius: 8px;
        font-weight: 800; opacity: 0; pointer-events: none; transition: opacity 0.3s;
        z-index: 200; box-shadow: 0 10px 30px rgba(0,0,0,0.5);
      }

      @keyframes wr-pop {
        0% { transform: scale(1); }
        50% { transform: scale(1.1); }
        100% { transform: scale(1); }
      }
      @keyframes wr-flip {
        0% { transform: rotateX(0); }
        50% { transform: rotateX(90deg); }
        100% { transform: rotateX(0); }
      }
      @keyframes wr-shake {
        0%, 100% { transform: translateX(0); }
        20%, 60% { transform: translateX(-5px); }
        40%, 80% { transform: translateX(5px); }
      }
    </style>

    <div class="wr-wrapper">
      <div class="wr-header">
        <div class="wr-score-box">Streak: <span id="wr-streak">0</span></div>
        <div class="wr-score-box" style="background: rgba(16, 185, 129, 0.2); color: #10B981; border-color: #10B981;">Best: <span id="wr-best">0</span></div>
      </div>
      
      <div class="wr-toast" id="wr-toast">Not enough letters</div>

      <div class="wr-board" id="wr-board">
        <!-- Rows generated by JS -->
      </div>

      <div class="wr-keyboard" id="wr-keyboard">
        <div class="wr-key-row">
          <button class="wr-key" data-key="Q">Q</button><button class="wr-key" data-key="W">W</button>
          <button class="wr-key" data-key="E">E</button><button class="wr-key" data-key="R">R</button>
          <button class="wr-key" data-key="T">T</button><button class="wr-key" data-key="Y">Y</button>
          <button class="wr-key" data-key="U">U</button><button class="wr-key" data-key="I">I</button>
          <button class="wr-key" data-key="O">O</button><button class="wr-key" data-key="P">P</button>
        </div>
        <div class="wr-key-row">
          <button class="wr-key" data-key="A">A</button><button class="wr-key" data-key="S">S</button>
          <button class="wr-key" data-key="D">D</button><button class="wr-key" data-key="F">F</button>
          <button class="wr-key" data-key="G">G</button><button class="wr-key" data-key="H">H</button>
          <button class="wr-key" data-key="J">J</button><button class="wr-key" data-key="K">K</button>
          <button class="wr-key" data-key="L">L</button>
        </div>
        <div class="wr-key-row">
          <button class="wr-key large" data-key="ENTER">ENTER</button>
          <button class="wr-key" data-key="Z">Z</button><button class="wr-key" data-key="X">X</button>
          <button class="wr-key" data-key="C">C</button><button class="wr-key" data-key="V">V</button>
          <button class="wr-key" data-key="B">B</button><button class="wr-key" data-key="N">N</button>
          <button class="wr-key" data-key="M">M</button>
          <button class="wr-key large" data-key="BACKSPACE">⌫</button>
        </div>
      </div>

      <!-- Game Over Overlay -->
      <div class="wr-overlay" id="wr-overlay">
        <div class="wr-title" id="wr-title">YOU WON!</div>
        <div style="color: #aaa; font-weight: 700; margin-bottom: 5px;">THE WORD WAS</div>
        <div class="wr-target" id="wr-target-display">APPLE</div>
        <button class="wr-btn" onclick="window.wrReset()">PLAY AGAIN</button>
        <button class="wr-btn" style="background: #333; box-shadow: none; color: white;" onclick="window.location.href='index.html'">BACK TO ARCADE</button>
      </div>
    </div>
  `;

  const WORDS = [
    "APPLE", "BRICK", "CRANE", "DANCE", "EAGLE", "FLAME", "GRAPE", "HEART", "IMAGE", "JUICE", 
    "KNIFE", "LEMON", "MANGO", "NIGHT", "OCEAN", "PIZZA", "QUEEN", "RIVER", "SNAKE", "TIGER", 
    "UNCLE", "VOICE", "WATER", "XENON", "YACHT", "ZEBRA", "GHOST", "TRAIN", "SHARK", "CLOUD", 
    "SMILE", "MAGIC", "MUSIC", "SPACE", "BEACH", "MONEY", "DREAM", "POWER", "WORLD", "LIGHT",
    "SUPER", "PLANT", "TABLE", "CHAIR", "CLOCK", "PHONE", "MOUSE", "BREAD", "SUGAR", "HONEY",
    "FROST", "STORM", "BLAZE", "ROBOT", "LASER", "ALIEN", "CHESS", "POKER", "SWORD", "SHIELD",
    "NINJA", "FAIRY", "DRINK", "GAMES", "PIXEL", "AUDIO", "VIDEO", "MOVIE", "TRACK", "GUEST", 
    "PARTY", "EVENT", "BRUSH", "PAINT", "COLOR", "SHADE", "BLACK", "WHITE", "GREEN", "ALERT",
    "ABOUT", "ABOVE", "ACTOR", "ADAPT", "ADMIT", "ADULT", "AFTER", "AGAIN", "AGENT", "AGREE",
    "AHEAD", "ALARM", "ALBUM", "ALIVE", "ALLOW", "ALONE", "ALONG", "ALTER", "AMONG", "ANGER",
    "ANGLE", "ANGRY", "APART", "AVOID", "AWARD", "AWARE", "BADLY", "BAKER", "BASIC", "BASIS",
    "BEAST", "BEGIN", "BLAME", "BLIND", "BLOCK", "BLOOD", "BOARD", "BRAIN", "BREAK", "BROWN",
    "BUILD", "BUYER", "CATCH", "CAUSE", "CHAIN", "CHART", "CHASE", "CHEAP", "CHECK", "CHEST",
    "CHIEF", "CHILD", "CHINA", "CLAIM", "CLASS", "CLEAN", "CLEAR", "CLOSE", "COACH", "COAST",
    "COUNT", "COURT", "COVER", "CRAZY", "CREAM", "CRIME", "CROSS", "CROWD", "CROWN", "CURVE",
    "CYCLE", "DAILY", "DEATH", "DELAY", "DEPTH", "DOUBT", "DRAFT", "DRAMA", "DRESS", "DRIVE",
    "EARLY", "EARTH", "EIGHT", "ELITE", "EMPTY", "ENEMY", "ENJOY", "ENTER", "ENTRY", "EQUAL",
    "ERROR", "EXACT", "EXIST", "EXTRA", "FAITH", "FALSE", "FAULT", "FIBER", "FIELD", "FIFTH",
    "FIFTY", "FIGHT", "FINAL", "FIRST", "FIXED", "FLASH", "FLEET", "FLOOR", "FLUID", "FOCUS",
    "FORCE", "FORTH", "FORTY", "FORUM", "FOUND", "FRAME", "FRANK", "FRAUD", "FRESH", "FRONT",
    "FRUIT", "FULLY", "FUNNY", "GIANT", "GIVEN", "GLASS", "GLOBE", "GOING", "GRACE", "GRADE",
    "GRAND", "GRANT", "GRASS", "GREAT", "GROSS", "GROUP", "GROWN", "GUARD", "GUESS", "GUIDE",
    "HAPPY", "HEAVY", "HENCE", "HORSE", "HOTEL", "HOUSE", "HUMAN", "IDEAL", "INDEX", "INNER",
    "INPUT", "ISSUE", "JOINT", "JUDGE", "KNOWN", "LABEL", "LARGE", "LATER", "LAUGH", "LAYER",
    "LEARN", "LEASE", "LEAST", "LEAVE", "LEGAL", "LEVEL", "LIMIT", "LOGIC", "LOOSE", "LUCKY",
    "MAJOR", "MAKER", "MARCH", "MATCH", "MAYOR", "MEANS", "METAL", "MIGHT", "MINOR", "MODEL",
    "MONTH", "MORAL", "MOTOR", "MOUNT", "MOUTH", "NEEDS", "NEVER", "NEWLY", "NOISE", "NORTH",
    "NOTED", "NOVEL", "NURSE", "OCCUR", "OFFER", "OFTEN", "ORDER", "OTHER", "OUGHT", "PANEL",
    "PAPER", "PEACE", "PHASE", "PHOTO", "PIECE", "PILOT", "PITCH", "PLACE", "PLAIN", "PLANE",
    "PLATE", "POINT", "POUND", "PRESS", "PRICE", "PRIDE", "PRIME", "PRINT", "PRIOR", "PRIZE",
    "PROOF", "PROUD", "PROVE", "QUICK", "QUIET", "QUITE", "RADIO", "RAISE", "RANGE", "RAPID",
    "RATIO", "REACH", "READY", "REFER", "RIGHT", "RIVAL", "ROUGH", "ROUND", "ROUTE", "ROYAL",
    "RURAL", "SCALE", "SCENE", "SCOPE", "SCORE", "SENSE", "SERVE", "SEVEN", "SHAPE", "SHARE",
    "SHARP", "SHEET", "SHELF", "SHELL", "SHIFT", "SHIRT", "SHOCK", "SHOOT", "SHORT", "SHOWN",
    "SIGHT", "SINCE", "SKILL", "SLEEP", "SLIDE", "SMALL", "SMART", "SMITH", "SMOKE", "SOLID",
    "SOLVE", "SORRY", "SOUND", "SOUTH", "SPARE", "SPEAK", "SPEED", "SPEND", "SPLIT", "SPOKE",
    "SPORT", "STAFF", "STAGE", "STAND", "START", "STATE", "STEAM", "STEEL", "STICK", "STILL",
    "STOCK", "STONE", "STORE", "STORY", "STRIP", "STUDY", "STUFF", "STYLE", "SUITE", "SWEET",
    "TASTE", "TAXES", "TEACH", "TEETH", "TEXAS", "THANK", "THEFT", "THEIR", "THEME", "THERE",
    "THESE", "THICK", "THING", "THINK", "THIRD", "THOSE", "THREE", "THROW", "TIGHT", "TIMES",
    "TITLE", "TODAY", "TOPIC", "TOTAL", "TOUCH", "TOUGH", "TOWER", "TRADE", "TREAT", "TREND",
    "TRIAL", "TRUST", "TRUTH", "TWICE", "UNDER", "UNDUE", "UNION", "UNITY", "UNTIL", "UPPER",
    "UPSET", "URBAN", "USAGE", "USUAL", "VALID", "VALUE", "VIRUS", "VISIT", "VITAL", "WEALTH",
    "WHERE", "WHICH", "WHILE", "WHOLE", "WOMAN", "WORRY", "WORSE", "WORST", "WORTH", "WOULD",
    "WOUND", "WRITE", "WRONG", "YIELD", "YOUNG", "YOUTH"
  ];

  let streak = parseInt(localStorage.getItem('wr-streak')) || 0;
  let best = parseInt(localStorage.getItem('wr-best')) || 0;
  
  let targetWord = "";
  let currentAttempt = 0;
  let currentLetter = 0;
  let grid = Array(6).fill().map(() => Array(5).fill(''));
  let gameOver = false;

  const elBoard = document.getElementById('wr-board');
  const elStreak = document.getElementById('wr-streak');
  const elBest = document.getElementById('wr-best');
  const elToast = document.getElementById('wr-toast');
  const elOverlay = document.getElementById('wr-overlay');
  
  elStreak.innerText = streak;
  elBest.innerText = best;

  function initBoard() {
    elBoard.innerHTML = '';
    for (let r = 0; r < 6; r++) {
      const row = document.createElement('div');
      row.className = 'wr-row';
      row.id = `row-${r}`;
      for (let c = 0; c < 5; c++) {
        const tile = document.createElement('div');
        tile.className = 'wr-tile';
        tile.id = `tile-${r}-${c}`;
        row.appendChild(tile);
      }
      elBoard.appendChild(row);
    }
  }

  function showToast(msg) {
    elToast.innerText = msg;
    elToast.style.opacity = '1';
    setTimeout(() => { elToast.style.opacity = '0'; }, 2000);
  }

  function handleKey(key) {
    if (gameOver) return;

    if (key === 'ENTER') {
      submitGuess();
    } else if (key === 'BACKSPACE' || key === 'DELETE') {
      if (currentLetter > 0) {
        currentLetter--;
        grid[currentAttempt][currentLetter] = '';
        updateTile(currentAttempt, currentLetter);
      }
    } else if (/^[A-Z]$/.test(key)) {
      if (currentLetter < 5) {
        grid[currentAttempt][currentLetter] = key;
        updateTile(currentAttempt, currentLetter);
        currentLetter++;
      }
    }
  }

  function updateTile(r, c) {
    const tile = document.getElementById(`tile-${r}-${c}`);
    tile.innerText = grid[r][c];
    if (grid[r][c]) {
      tile.classList.add('filled');
    } else {
      tile.classList.remove('filled');
    }
  }

  async function submitGuess() {
    if (currentLetter < 5) {
      showToast('Not enough letters');
      return;
    }

    const guess = grid[currentAttempt].join('');
    
    // Check if it's a real word using API
    if (!WORDS.includes(guess)) {
      try {
        const res = await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${guess}`);
        if (res.status === 404) {
          showToast('Not in word list');
          // Add shake animation
          const row = document.getElementById(`row-${currentAttempt}`);
          row.style.animation = 'wr-shake 0.4s';
          setTimeout(() => row.style.animation = '', 400);
          return;
        }
      } catch(e) {
        // Ignore API failures and let them guess to avoid game breaking
      }
    }
    
    // Check colors
    const targetArr = targetWord.split('');
    const guessArr = guess.split('');
    const colors = Array(5).fill('absent');
    
    // Pass 1: Correct
    for (let i = 0; i < 5; i++) {
      if (guessArr[i] === targetArr[i]) {
        colors[i] = 'correct';
        targetArr[i] = null; // consume
      }
    }
    
    // Pass 2: Present
    for (let i = 0; i < 5; i++) {
      if (colors[i] === 'correct') continue;
      const idx = targetArr.indexOf(guessArr[i]);
      if (idx !== -1) {
        colors[i] = 'present';
        targetArr[idx] = null; // consume
      }
    }

    // Animate and apply colors
    const row = document.getElementById(`row-${currentAttempt}`);
    const tiles = row.children;
    
    for (let i = 0; i < 5; i++) {
      setTimeout(() => {
        tiles[i].style.animation = 'wr-flip 0.5s ease';
        setTimeout(() => {
          tiles[i].classList.add(colors[i]);
          updateKeyboardColor(guessArr[i], colors[i]);
        }, 250);
      }, i * 200);
    }

    setTimeout(() => {
      if (guess === targetWord) {
        endGame(true);
      } else {
        currentAttempt++;
        currentLetter = 0;
        if (currentAttempt >= 6) {
          endGame(false);
        }
      }
    }, 5 * 200 + 300);
  }

  function updateKeyboardColor(letter, color) {
    const key = document.querySelector(`.wr-key[data-key="${letter}"]`);
    if (!key) return;
    
    // Priority: correct > present > absent
    if (key.classList.contains('correct')) return;
    if (key.classList.contains('present') && color === 'absent') return;
    
    key.classList.remove('present', 'absent');
    key.classList.add(color);
  }

  function endGame(win) {
    gameOver = true;
    document.getElementById('wr-target-display').innerText = targetWord;
    
    if (win) {
      document.getElementById('wr-title').innerText = "YOU WON! 🎉";
      document.getElementById('wr-title').style.color = "#10B981";
      streak++;
      if (streak > best) {
        best = streak;
        localStorage.setItem('wr-best', best);
      }
      localStorage.setItem('wr-streak', streak);
      if (window.saveScore && streak > 0) {
        window.saveScore('Word Rush', streak);
      }
    } else {
      document.getElementById('wr-title').innerText = "GAME OVER 💀";
      document.getElementById('wr-title').style.color = "#EF4444";
      streak = 0;
      localStorage.setItem('wr-streak', streak);
    }
    
    elStreak.innerText = streak;
    elBest.innerText = best;
    
    setTimeout(() => {
      elOverlay.style.display = 'flex';
    }, 500);
  }

  window.wrReset = function() {
    elOverlay.style.display = 'none';
    targetWord = WORDS[Math.floor(Math.random() * WORDS.length)];
    currentAttempt = 0;
    currentLetter = 0;
    grid = Array(6).fill().map(() => Array(5).fill(''));
    gameOver = false;
    
    initBoard();
    
    // Reset keyboard
    document.querySelectorAll('.wr-key').forEach(k => {
      k.classList.remove('correct', 'present', 'absent');
    });
  };

  // Keyboard Event Listeners
  document.querySelectorAll('.wr-key').forEach(btn => {
    btn.addEventListener('click', (e) => {
      handleKey(e.target.dataset.key);
    });
  });

  // Physical Keyboard
  const handlePhysicalKey = (e) => {
    if (e.ctrlKey || e.altKey || e.metaKey) return;
    const key = e.key.toUpperCase();
    if (/^[A-Z]$/.test(key) || key === 'ENTER' || key === 'BACKSPACE') {
      handleKey(key);
    }
  };
  document.addEventListener('keydown', handlePhysicalKey);
  
  // Cleanup listener when leaving
  const observer = new MutationObserver((mutations) => {
    if (!document.contains(container)) {
      document.removeEventListener('keydown', handlePhysicalKey);
      observer.disconnect();
    }
  });
  observer.observe(document.body, { childList: true, subtree: true });

  // Start
  window.wrReset();
}
